#
#
# Don't Change This!
# This value gets updated automatically
version: 1.0
#
# Set the default menu that will only anytime a player executes /h
default-menu: particles.yml
#
# Set the default messages file.
default-messages: default_messages.yml
#
# Loads the included menus:
# - particles.yml
load-included-menus: true
#
# Loads the included custom types:
# - butterfly_wings_colorable.png
# - vampire_wings.png
load-included-custom-types: true
#
# Choose which worlds this plugin should ignore
disabled-worlds: []
#
# Checks to see if a player has permission to use particles for the world they're in.
check-world-permission: false
#
# Closes the players menu any time they equip a hat
close-menu-on-equip: true
#
# Use %currency% in your item descriptions to utilize this value
currency: $
#
# Let menus dynamically update their content (Cosmetic only)
live-menus: true
#
# Set how often menus are updated (1 = fastest)
live-menu-update-frequency: 5
#
# Set the maximum amount of hats a player can be wearing at once. Range is (1 - 28)
max-hats: 7
#
database:
  #
  # Choose how the plugin saves data
  # Supported types are [yml, mysql]
  type: yml
  #
  # MySQL properties
  username: username
  password: password
  hostname: host
  port: 3306
  database: ParticleHats
#
flags:
  #
  # Enable Vault and use any economy plugin you want to unlock hats
  vault: false
  #
  # Enable PlayerPoints economy
  playerpoints: false
  #
  # Allow players to unlock hats using their experience points
  experience: false
  #
  # Allow players to equip hats based on permissions
  permission: true
  #
  # Use a supported vanish plugin, and hide particles anytime a player vanishes
  # Supported plugins are: SuperVanish, PremiumVanish, & VanishNoPacket
  vanish: false
#
afk:
  # Set how many seconds the plugin will wait before marking a player as AFK
  cooldown: 1
#
combat:
  # Set how many seconds the plugin will wait before making a player as peaceful
  cooldown: 1
  #
  # These combat flags allow you to specify which types of entities to check for when a player is attacking
  #
  # Disable a players peaceful status when they attack other players
  check-players: true
  #
  # Disable a players peaceful status when they attack monsters
  check-monsters: true
  #
  # Disable a players peaceful status when they attack animals
  check-animals: false
  #
  # Disable a players peaceful status when they attack villagers
  check-npc: false
#
menu:
  #
  # Hat icons will be replaced if the player does not have permission to equip them
  lock-hats-without-permission: false
  #
  locked-item:
    #
    # This item will replace the hats normal icon
    id: LAPIS_LAZULI
    #
    # This title will replace the hats normal display name
    title: &8Locked
  #
  # Open a menu when the player right clicks while holding an item
  open-menu-with-item:
    #
    enabled: false
    #
    # The default menu the player will open
    default-menu: particles
    #
    # Opens the players group menu instead of the default_menu
    use-player-group: true
    #
    # Which item the player needs to interact with
    id: NETHER_STAR
    damage-value: 0
  #
  sound:
    #
    # Enable sound
    # A sound effect players anytime the player uses a menu
    enabled: true;
    #
    # Name of the sound you want to play
    id: UI_BUTTON_CLICK
    #
    # Ranges from 0.0 to 1.0
    volume: 1.0
    #
    # Ranges from 0.0 to 2.0
    pitch: 1.0
#
editor:
  #
  # Whenever the user is asked for input, they'll be notified from the actionbar (Text that appears above the players hotbar)
  # If this is disabled, then input will be notified via chat
  use-actionbar: true
  #
  # Set how long to wait before canceling a meta edit
  meta-time-limit: 30
  #
  sound:
    #
    enabled: true
    #
    id: BLOCK_METAL_PLACE
    #
    # Ranges from 0.0 to 1.0
    volume: 1.0
    #
    # Ranges from 0.0 to 2.0
    pitch: 1.0
    #
    # Some menus will alter the sound to reflect the current action (eg: increasing / decreasing a value, deleting an item)
    modifier: 0.25