name: ParticleHats
main: com.mediusecho.particlehats.ParticleHats
version: 4.0.0-RC1
api-version: 1.13
author: MediusEcho
softdepend: [Vault, SuperVanish, PremiumVanish, VanishNoPacket, PlayerPoints]
commands:
  h:
    description: Main command for ParticleHats
    aliases: ph
    