name: ParticleHats
main: com.mediusecho.particlehats.ParticleHats
version: 4.0
api-version: 1.13
author: MediusEcho
softdepend: [Vault, SuperVanish, PremiumVanish, VanishNoPacket, PlayerPoints]
commands:
  h:
    description: Main command for ParticleHats
    aliases: ph
  hats:
    description: Allows players to manage their equipped hats